name: news_curation
description: Curating news from noisy feeds.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.6.0-0.0.pre"

dependencies:
  flutter:
    sdk: flutter
  
  fast_immutable_collections: any
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  freezed: any
  json_serializable: any

flutter:
  uses-material-design: true
