name: curatable
description: Curating news from noisy feeds.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.6.0-0.0.pre"

dependencies:
  flutter:
    sdk: flutter

  url_launcher:
  firebase_core:
  cloud_firestore:
  
  fast_immutable_collections:
  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
