name: backend
description: a backend for news_curation app
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0
  googleapis:
  googleapis_auth:
  http:
  collection:

dev_dependencies:
  lints:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  test: ^1.15.7
  test_process: ^2.0.0
